1. Create a 1D NumPy Array:

In [1]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Inspection and Properties
1. Shapes

In [2]:
print(temperatures_w1.shape)

(7,)

2. Data Type (dtype)

In [3]:
print(temperatures_w1.dtype)

float64

3. Number of elements in the Array

In [4]:
print(temperatures_w1.size)

7

3. Array Operations:

In [5]:
temperatures_f = (temperatures_w1 * 9/5) + 32                      # Formula used -- > Fahrenheit = (Celsius × 9/5) + 32

print(temperatures_f)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Find the maximum, minimum, and mean temperatures for the week.

In [6]:
print(np.max(temperatures_w1))             # To find maximum temperature

26.1

In [7]:
print(np.min(temperatures_w1))       # To find Minimum temperature

20.8

In [8]:
print(np.mean(temperatures_w1))      # To find the average or mean temperature

23.542857142857144

4. Array Slicing and Indexing:

In [9]:
print(temperatures_w1[:3])        # temperatures for the first three days of the week.

[22.5 25.3 20.8]

In [10]:
print(temperatures_w1[-2:])       # temperatures for the last two days.

[24.8 21.9]

In [11]:
print(temperatures_w1[2:5])           # temperatures for the middle three days of the week.

[20.8 23.4 26.1]

5. Create a 2D Array:

In [12]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],             # Temperature of 2 different weeks
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

6. Inspect and Slice the 2D Array:

In [13]:
print(temperatures.shape)     # Shapes
print(temperatures.dtype)     # Datatype
print(temperatures.size)      # Total number of elements in temperature array that is size

(2, 7)
float64
14

Extract the temperatures for each week and the weekends (last two days) for both weeks.

In [14]:
print(temperatures[0])              # week 1 temperature

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [15]:
print(temperatures[1])              # week 2 temperature

[19.2 22.5 21.3 24.  23.5 22.8 20.1]

In [16]:
print(temperatures[0, -2:])         # Last 2 days of week 1, Temperature(0) represents week 1

[24.8 21.9]

In [17]:
print(temperatures[1, -2:])         # Last 2 days of week 2, Temperature(1) represents week 2

[22.8 20.1]

Pandas Series:
1. Creating Pandas Series:

In [18]:
import pandas as pd

In [19]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

2. Indexing and Slicing:

In [20]:
print(marks.iloc[0])       # .iloc will tell the integer location and [0] will indicate first position

95

In [21]:
# marks = pd.Series([95, 90, 88, 85, 80], index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"])

marks.loc[["Rank1", "Rank2", "Rank3"]]    # .loc is used when we want to select data using the index LABEL.Here we have to find top 3 Rank

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [22]:
marks.iloc[2]      # .loc[2] will give the value which is at position 2.

np.int64(89)

In [23]:
marks[marks > 90]      # To find the marks greater than 90

Rank1    95
Rank2    92
dtype: int64

3. Manipulating Series:

In [ ]:
marks.loc["Rank1"] = 100          # to change Rank1 from 95 to 100

In [ ]:
marks          # This will give the output after updating Rank1 as 100.

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
marks = marks.drop("Rank5")        # remove the entry whose label is Rank5.

In [ ]:
marks     # output shows only entry till Rank4

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [ ]:
cgpa = marks / 10     # CGPA means Cumulative Grade Point Average    100/10 , 92/10 , 89/10 , 85/10  --> 10.0, 9.2, 8.9, 8.5

In [ ]:
cgpa    # CGPA is a grade-point value used to represent a student's academic performance.

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

Pandas DataFrame:
1. Creating Pandas DataFrame:

In [31]:
import pandas as pd

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": ["Electronics", "Clothing", "Electronics", "Furniture", "Clothing", "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"],
    "Region": ["North", "South", "North", "East", "West", "North", "East", "West", "South", "North"],
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

In [ ]:
transactions    # This will give the output separately as shown below

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

2. Data Exploration:

In [ ]:
transactions.head()        # head() means "show me the beginning of the DataFrame." that is first 5 Rows

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [ ]:
transactions.tail()    # tail() means this will show the last 5 rows of our DataFrame.

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
transactions.shape        # This tells us how many rows and columns are in our DataFrame.

(10, 4)

In [ ]:
transactions.columns        # This will show the names of all 4 columns.

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [ ]:
transactions.dtypes   # This will tell us what type of data is stored in each column.

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [ ]:
transactions[["ProductCategory", "Amount"]]          #  Display only the 'ProductCategory' and 'Amount' columns.

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
transactions.iloc[:, -3:]        # using iloc for this because we're selecting columns by their position.

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
transactions[(transactions["Region"] == "North") & (transactions["Amount"] > 200)]     # Region = North , Amount > 200

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
transactions["ProductCategory"].value_counts()            # to Count how many times each product category appears.

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
transactions["Region"].unique()      # This means showing each region only once, without duplicates.

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [ ]:
transactions.groupby("Region")["Amount"].mean()        # For each region we have to calculate the average (mean) transaction amount.

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

3. Manipulating the DataFrame:

In [ ]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165  

#  We need to change the Amount of transaction 102 to 165. Find TransactionID 102 → go to its Amount → change it to 165.

In [ ]:
transactions[transactions['TransactionID'] == 102]       # previously the amount for 102 row was 150, we changed it to 165

   TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165

In [ ]:
transactions['Discount'] = transactions['Amount'] * 0.10          # Add new column "Discount" which shows the discounted amount.

In [ ]:
transactions    # To check the output

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

Remove the row with TransactionID 109.

In [50]:
transactions = transactions[transactions['TransactionID'] != 109]

In [51]:
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

Delete the 'Discount' column from the DataFrame.

In [ ]:
transactions = transactions.drop('Discount', axis=1)     # to delete the discount column use "drop".

In [ ]:
transactions          # check the output, here the Discount column is removed

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400